name: Build and Publish CSharp Workflow runner

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'csharp/**'
      - '.github/workflows/workflowrunner-build.yml'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'csharp/**'
      - '.github/workflows/workflowrunner-build.yml'
  release:
    types: [published, created]

env:
  DOCKER_IMAGE: your-dockerhub-username/train-solver-wf-runner-cs
  DOTNET_VERSION: 8.0
  VERSION: ${{ github.event.release.tag_name || github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'release'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: csharp/src/WorkflowRunner/Dockerfile
          push: true
          build-args: |
            DOTNET_VERSION=${{ env.DOTNET_VERSION }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
             ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 